### ISSUE TITLE
Authorization url not accepting AuthCredentials object

### ISSUE THREAD

**Issue by RyRy79261** [warrenbuckley/Umbraco-JWT-AuthTokens#12]
I've attempted to authorise a member http://localhost:55778/umbraco/TokenAuth/SecureApi/AuthoriseMember?auth={"Username":"derp@derp.com",""Password":"password123"}

But the function sees the "auth" variable as empty.

**Comment by codenakama** [comment]
@RyRy79261  you have to POST to http://localhost:55778/umbraco/TokenAuth/SecureApi/AuthoriseMember

and in the body of your request you have to pass the json 

`{"Username":"derp@derp.com",""Password":"password123"}`

Check this collection on postman and let me know if you were able or not - https://www.getpostman.com/collections/8a690fc30e88af6f3363

**Comment by RyRy79261** [comment]
Hi there, 

So I ended up making my own implementation of that authorisemember as this is for an angular app.

**Comment by codenakama** [comment]
@RyRy79261 can the issue be closed?

**Comment by RyRy79261** [comment]
Yep
