### ISSUE TITLE
Could be used/extend with OAuth Social login?

### ISSUE THREAD

**Issue by biapar** [warrenbuckley/Umbraco-JWT-AuthTokens#7]
Could be used/extend with OAuth Social login?

**Comment by warrenbuckley** [comment]
I would recommend then looking at IdentityServer and the Umbraco project IdentityExtensions as I have no plans in the project to do so.

**Comment by biapar** [comment]
IdentityServer as external server? I wish to use Umbraco member.
My idea is to extend your JWT if it's possible to do.
I installed IdentityExtensions but I don't understand where to extend it to add the member authorization becasuse IdentityExtensions are only for the Umbraco users.

**Comment by warrenbuckley** [comment]
Sorry I don't have time to help you with this. I recommend talking with others in the Umbraco members community on our.umbraco.org to see if anyone else has done this or has solutions to your problem.
